const DB_KEY='wintercamp_rental_v1';
const seed={bookings:[
{id:1001,name:'أحمد الشهري',phone:'0555123456',device:'2 سماعات',location:'أبها - حي العرين',date:'2026-08-08',agreed:500,paid:200,notes:''},
{id:1002,name:'محمد القحطاني',phone:'',device:'سماعة بلوتوث',location:'خميس مشيط',date:'2026-08-09',agreed:300,paid:300,notes:''},
{id:1003,name:'سعيد آل علي',phone:'',device:'باقة كاملة',location:'أبها - طريق المية',date:'2026-08-11',agreed:600,paid:0,notes:''}],
expenses:[{id:1,item:'صيانة سماعات',amount:300,date:'2026-08-03'},{id:2,item:'وقود',amount:150,date:'2026-08-04'}],devices:[{id:1,name:'RCF 715-A',qty:2},{id:2,name:'سماعة بلوتوث',qty:1},{id:3,name:'MG-12XU ميكسر',qty:1},{id:4,name:'ميكروفون',qty:4}]};
let db=load();let currentPage='home';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(DB_KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function money(n){return new Intl.NumberFormat('ar-SA').format(Number(n||0))+' ر.س'}
function hijri(date){try{return new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{day:'numeric',month:'long',year:'numeric'}).format(new Date(date+'T12:00:00'))}catch{return date}}
function hijriShort(date){try{return new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(date+'T12:00:00'))}catch{return date}}
function dayName(date){return new Intl.DateTimeFormat('ar-SA',{weekday:'long'}).format(new Date(date+'T12:00:00'))}
function totals(){const revenue=db.bookings.reduce((s,b)=>s+Number(b.agreed||0),0);const paid=db.bookings.reduce((s,b)=>s+Number(b.paid||0),0);const expenses=db.expenses.reduce((s,e)=>s+Number(e.amount||0),0);return{revenue,paid,remaining:revenue-paid,expenses,profit:revenue-expenses}}
function status(b){const r=Number(b.agreed)-Number(b.paid);return r<=0?['مدفوعة بالكامل','paid']:Number(b.paid)>0?['مدفوعة جزئياً','partial']:['لم يتم الدفع','unpaid']}
function todayISO(){return new Date().toISOString().slice(0,10)}
function render(){document.getElementById('pageTitle').textContent=({home:'الرئيسية',bookings:'الحجوزات',expenses:'المصاريف',reports:'التقارير',devices:'الأجهزة',invoices:'الفواتير',settings:'الإعدادات'})[currentPage]||'الرئيسية'; $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage)); const main=$('#mainContent');main.innerHTML=({home:homeView,bookings:bookingsView,expenses:expensesView,reports:reportsView,devices:devicesView,invoices:invoicesView,settings:settingsView}[currentPage]||homeView)();bindViewEvents()}
function homeView(){const t=totals();const upcoming=[...db.bookings].sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4);return `<section class="hero"><div><h2>مرحباً بك 👋</h2><p>ملخص نشاط Winter Camp</p></div></section><div class="cards"><div class="stat-card"><span class="label">إجمالي الإيرادات</span><span class="value green">${money(t.revenue)}</span><span class="unit">الحجوزات</span></div><div class="stat-card"><span class="label">إجمالي المصاريف</span><span class="value red">${money(t.expenses)}</span><span class="unit">المسجلة</span></div><div class="stat-card"><span class="label">صافي الربح</span><span class="value blue">${money(t.profit)}</span><span class="unit">قبل التحصيل</span></div><div class="stat-card"><span class="label">المتبقي للتحصيل</span><span class="value gold">${money(t.remaining)}</span><span class="unit">من العملاء</span></div></div><div class="section-head"><h3>الحجوزات القادمة</h3><button class="link-btn" data-go="bookings">عرض الكل</button></div>${upcoming.map(bookingCard).join('')||'<div class="empty">لا توجد حجوزات</div>'}`}
function bookingCard(b){const [txt,cls]=status(b),remaining=Number(b.agreed)-Number(b.paid);return `<article class="booking-card"><div class="booking-top"><div><div class="booking-name">${esc(b.name)}</div><div class="booking-meta">${esc(b.device)} · ${esc(b.location)}<br>${dayName(b.date)} · ${hijriShort(b.date)}</div><span class="badge ${cls}">${txt}</span></div><div class="amount">${money(b.agreed)}<div class="booking-meta">متبقي <span class="red">${money(Math.max(0,remaining))}</span></div></div></div><div class="card-actions"><button class="small-btn" data-detail="${b.id}">تفاصيل</button><button class="small-btn primary" data-invoice="${b.id}">عرض الفاتورة</button></div></article>`}
function bookingsView(){return `<div class="section-head"><h3>جميع الحجوزات</h3><span>${db.bookings.length} حجز</span></div>${[...db.bookings].sort((a,b)=>b.date.localeCompare(a.date)).map(bookingCard).join('')||'<div class="empty">لم تسجل حجوزات بعد</div>'}`}
function expensesView(){return `<div class="section-head"><h3>المصاريف</h3><span class="red">${money(totals().expenses)}</span></div>${[...db.expenses].sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<div class="expense-row"><div><strong>${esc(e.item)}</strong><small>${hijriShort(e.date)}</small></div><div><strong class="red">${money(e.amount)}</strong><button class="icon-btn" data-del-expense="${e.id}">⋮</button></div></div>`).join('')||'<div class="empty">لا توجد مصاريف</div>'}`}
function reportsView(){const t=totals(),max=Math.max(t.revenue,t.expenses,t.profit,1);return `<div class="section-head"><h3>التقرير الشهري (هجري)</h3></div><div class="report-box"><div class="bar-line"><span>الإيرادات</span><div class="track"><div class="fill" style="width:${t.revenue/max*100}%;background:var(--green)"></div></div><b>${money(t.revenue)}</b></div><div class="bar-line"><span>المصاريف</span><div class="track"><div class="fill" style="width:${t.expenses/max*100}%;background:var(--red)"></div></div><b>${money(t.expenses)}</b></div><div class="bar-line"><span>صافي الربح</span><div class="track"><div class="fill" style="width:${Math.max(0,t.profit)/max*100}%;background:var(--blue)"></div></div><b>${money(t.profit)}</b></div><div class="bar-line"><span>المتبقي</span><div class="track"><div class="fill" style="width:${t.remaining/max*100}%;background:var(--gold)"></div></div><b>${money(t.remaining)}</b></div></div><div class="section-head"><h3>ملخص</h3></div><div class="cards"><div class="stat-card"><span class="label">الحجوزات</span><span class="value">${db.bookings.length}</span></div><div class="stat-card"><span class="label">المصاريف</span><span class="value">${db.expenses.length}</span></div></div>`}
function devicesView(){return `<div class="section-head"><h3>الأجهزة</h3></div>${db.devices.map(d=>`<div class="device-card"><div class="booking-top"><strong>${esc(d.name)}</strong><span>${d.qty} قطعة</span></div></div>`).join('')}`}
function invoicesView(){return `<div class="section-head"><h3>الفواتير</h3></div>${[...db.bookings].reverse().map(b=>`<div class="invoice-row"><div><strong>فاتورة #${String(b.id).padStart(4,'0')}</strong><small>${esc(b.name)} · ${hijriShort(b.date)}</small></div><button class="small-btn primary" data-invoice="${b.id}">عرض</button></div>`).join('')||'<div class="empty">لا توجد فواتير</div>'}`}
function settingsView(){return `<div class="section-head"><h3>الإعدادات</h3></div><div class="device-card"><strong>التاريخ</strong><p class="booking-meta">هجري - تقويم أم القرى</p></div><div class="device-card"><strong>حفظ البيانات</strong><p class="booking-meta">محلي داخل الجهاز باستخدام التخزين المحلي.</p></div><button class="submit-btn" id="settingsExport">تصدير نسخة احتياطية</button>`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function bindViewEvents(){$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-detail]').forEach(b=>b.onclick=()=>showDetail(+b.dataset.detail));$$('[data-invoice]').forEach(b=>b.onclick=()=>showInvoice(+b.dataset.invoice));$$('[data-del-expense]').forEach(b=>b.onclick=()=>deleteExpense(+b.dataset.delExpense));const ex=$('#settingsExport');if(ex)ex.onclick=exportData}
function go(p){currentPage=p;render()}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modalBackdrop').classList.remove('hidden');$('#modal').classList.remove('hidden')}
function closeModal(){$('#modalBackdrop').classList.add('hidden');$('#modal').classList.add('hidden')}
function showDetail(id){const b=db.bookings.find(x=>x.id===id);if(!b)return;openModal('تفاصيل الحجز',`<div class="device-card"><p><b>العميل:</b> ${esc(b.name)}</p><p><b>الجهاز:</b> ${esc(b.device)}</p><p><b>الموقع:</b> ${esc(b.location)}</p><p><b>اليوم:</b> ${dayName(b.date)}</p><p><b>التاريخ:</b> ${hijri(b.date)}</p><p><b>المتفق عليه:</b> <span class="green">${money(b.agreed)}</span></p><p><b>الواصل:</b> <span class="blue">${money(b.paid)}</span></p><p><b>المتبقي:</b> <span class="red">${money(Math.max(0,b.agreed-b.paid))}</span></p></div><div class="card-actions"><button class="small-btn primary" id="detailInvoice">عرض الفاتورة</button><button class="small-btn" id="editBooking">تعديل</button><button class="small-btn danger-btn" id="deleteBooking">حذف</button></div>`);$('#detailInvoice').onclick=()=>showInvoice(id);$('#editBooking').onclick=()=>openBookingForm(b);$('#deleteBooking').onclick=()=>{if(confirm('حذف الحجز؟')){db.bookings=db.bookings.filter(x=>x.id!==id);save();closeModal();render();toast('تم حذف الحجز')}}}
function showInvoice(id){const b=db.bookings.find(x=>x.id===id);if(!b)return;const remaining=Math.max(0,b.agreed-b.paid);openModal('الفاتورة',`<div class="invoice-paper" id="invoicePaper"><div class="invoice-brand"><div><h2 style="margin:0">فاتورة</h2><small>رقم #${String(b.id).padStart(4,'0')}<br>${hijriShort(b.date)}</small></div><img src="logo.png" alt="Winter Camp"></div><p><b>العميل:</b> ${esc(b.name)}</p><p><b>الموقع:</b> ${esc(b.location)}</p><table><thead><tr><th>الصنف</th><th>الكمية</th><th>الإجمالي</th></tr></thead><tbody><tr><td>${esc(b.device)}</td><td>1</td><td>${money(b.agreed)}</td></tr></tbody></table><p>المبلغ المتفق عليه: <b>${money(b.agreed)}</b></p><p>الواصل: <b>${money(b.paid)}</b></p><p>المتبقي: <b>${money(remaining)}</b></p><div class="invoice-total"><span>الإجمالي</span><span>${money(b.agreed)}</span></div><p style="margin-bottom:0;font-size:12px">شكراً لتعاملكم معنا</p></div><div class="invoice-actions"><button id="printInvoice">طباعة</button><button id="shareInvoice">مشاركة</button><button id="closeInvoice">إغلاق</button></div>`);$('#printInvoice').onclick=()=>window.print();$('#shareInvoice').onclick=()=>shareBooking(b);$('#closeInvoice').onclick=closeModal}
function shareBooking(b){const txt=`Winter Camp\nفاتورة #${b.id}\nالعميل: ${b.name}\nالتاريخ: ${hijriShort(b.date)}\nالإجمالي: ${money(b.agreed)}\nالواصل: ${money(b.paid)}\nالمتبقي: ${money(Math.max(0,b.agreed-b.paid))}`;if(navigator.share)navigator.share({title:'فاتورة Winter Camp',text:txt});else{navigator.clipboard?.writeText(txt);toast('تم نسخ بيانات الفاتورة')}}
function openBookingForm(existing=null){const b=existing||{name:'',phone:'',device:'',location:'',date:todayISO(),agreed:'',paid:'',notes:''};openModal(existing?'تعديل الحجز':'إضافة حجز',`<form id="bookingForm" class="form-grid"><label>اسم العميل<input name="name" required value="${esc(b.name)}"></label><label>رقم التواصل<input name="phone" inputmode="tel" value="${esc(b.phone)}"></label><label>نوع الجهاز<select name="device" required><option value="">اختر الجهاز</option>${db.devices.map(d=>`<option ${b.device===d.name?'selected':''}>${esc(d.name)}</option>`).join('')}<option ${b.device==='2 سماعات'?'selected':''}>2 سماعات</option><option ${b.device==='باقة كاملة'?'selected':''}>باقة كاملة</option></select></label><label>الموقع<input name="location" required value="${esc(b.location)}"></label><label>التاريخ<input name="date" type="date" required value="${b.date}"></label><div class="form-row"><label>السعر المتفق عليه<input name="agreed" inputmode="decimal" type="number" min="0" required value="${b.agreed}"></label><label>الواصل<input name="paid" inputmode="decimal" type="number" min="0" value="${b.paid}"></label></div><label>ملاحظات<textarea name="notes">${esc(b.notes)}</textarea></label><button class="submit-btn" type="submit">${existing?'حفظ التعديلات':'حفظ الحجز'}</button></form>`);$('#bookingForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);const obj=Object.fromEntries(f.entries());obj.agreed=Number(obj.agreed);obj.paid=Number(obj.paid||0);if(existing){Object.assign(existing,obj)}else{obj.id=Date.now();db.bookings.push(obj)}save();closeModal();render();toast(existing?'تم تحديث الحجز':'تم حفظ الحجز')}}
function openExpenseForm(){openModal('إضافة مصروف',`<form id="expenseForm" class="form-grid"><label>بند المصروف<input name="item" required placeholder="مثال: وقود"></label><label>المبلغ<input name="amount" type="number" inputmode="decimal" min="0" required></label><label>التاريخ<input name="date" type="date" required value="${todayISO()}"></label><button class="submit-btn">حفظ المصروف</button></form>`);$('#expenseForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget).entries());o.id=Date.now();o.amount=Number(o.amount);db.expenses.push(o);save();closeModal();render();toast('تم حفظ المصروف')}}
function deleteExpense(id){if(confirm('حذف المصروف؟')){db.expenses=db.expenses.filter(x=>x.id!==id);save();render();toast('تم الحذف')}}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='wintercamp-backup.json';a.click();URL.revokeObjectURL(a.href);toast('تم تجهيز النسخة الاحتياطية')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),1800)}
function toggleMenu(show){$('#sideSheet').classList.toggle('hidden',!show);$('#sheetBackdrop').classList.toggle('hidden',!show)}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#fabBtn').onclick=()=>currentPage==='expenses'?openExpenseForm():openBookingForm();$('#menuBtn').onclick=()=>toggleMenu(true);$('#closeMenu').onclick=()=>toggleMenu(false);$('#sheetBackdrop').onclick=()=>toggleMenu(false);$$('[data-sheet-page]').forEach(b=>b.onclick=()=>{toggleMenu(false);go(b.dataset.sheetPage)});$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=closeModal;$('#exportBtn').onclick=exportData;$('#backupBtn').onclick=exportData;$('#importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!d.bookings||!d.expenses)throw 0;db=d;save();render();toggleMenu(false);toast('تم استيراد البيانات')}catch{alert('ملف النسخة الاحتياطية غير صالح')}};
$('#hijriToday').textContent=hijri(todayISO());if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();
